In [4]:
import numpy as np


In [5]:
#1.	write a program that constructs a 3d array of dimensions 4X2X3.Initialize array to some values.
#Find maximum along each axis.

arr1=np.ones((4,2,3)) ; arr1


array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [6]:
arr1.ndim

3

In [7]:
arr1 =np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]],[[13,14,15],[16,17,18]],[[19,20,21],[22,23,24]]]);arr1

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24]]])

In [8]:
maximum_rows=arr1.max(axis=1)
print(maximum_rows)
print("----------------------------")
maximum_column=arr1.max(axis=0)
print(maximum_column)

[[ 4  5  6]
 [10 11 12]
 [16 17 18]
 [22 23 24]]
----------------------------
[[19 20 21]
 [22 23 24]]


In [9]:
minimum_rows=arr1.min(axis=1)
print(minimum_rows)
print("-----------------")
minimum_columns=arr1.min(axis=0)
print(minimum_columns)

[[ 1  2  3]
 [ 7  8  9]
 [13 14 15]
 [19 20 21]]
-----------------
[[1 2 3]
 [4 5 6]]


In [10]:
#a
array1=np.full((10),5);array1

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [11]:
#b
memory_size=array1.nbytes
print(memory_size)
memory_size_of_element=memory_size/array1.size
print(memory_size_of_element)

40
4.0


In [12]:
#c
array2=np.linspace(0,90,10);array2

array([ 0., 10., 20., 30., 40., 50., 60., 70., 80., 90.])

In [13]:
#d
c=np.flip(array2);c

array([90., 80., 70., 60., 50., 40., 30., 20., 10.,  0.])

In [14]:
#e
array3=np.add(array1,array2);array3

array([ 5., 15., 25., 35., 45., 55., 65., 75., 85., 95.])

In [15]:
arr3=np.zeros((8,8));arr3

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [16]:
arr3[::2,::2]=1;arr3

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [17]:
arr3[1::2,1::2]=1;arr3

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])

In [38]:
DS_emp=np.arange(1,201)
print("DS_emp--->",DS_emp)
DE_emp=np.arange(201,401);print("DE_emp-->",DE_emp)
DA_emp=np.arange(401,601)
print("DA_rmp---->",DA_emp)

DS_emp---> [  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107 108
 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125 126
 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143 144
 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161 162
 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179 180
 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197 198
 199 200]
DE_emp--> [201 202 203 204 205 206 207 208 209 210 211 212 213 214 215 216 217 218
 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233 234 235 236
 237 238 239 240 241

In [39]:
DS_sal=np.random.randint(20000,50000,200)
print("DS_sal")
print(DS_sal)
DE_sal=DS_sal*1.5
print("DE_sal")
print(DE_sal)
DA_sal=DS_sal+2000
print("DA_sal")
print(DA_sal)

DS_sal
[41203 22422 44249 29024 29459 47183 24337 27394 37462 23547 31118 37024
 26634 30927 42744 24510 34176 29697 27210 35295 21939 32045 47184 42906
 27492 43270 38393 22224 38837 24122 38183 43588 25958 26739 30593 20183
 35402 31119 40117 26601 33125 35433 26616 40275 42913 32257 43190 34190
 42167 27524 43076 22233 48355 20627 27585 46623 22103 33880 42662 46210
 37662 31334 48492 41658 23818 29033 36874 22221 36378 27036 22708 20290
 27247 45206 37325 47921 49725 40635 32947 26718 33188 47530 49676 29690
 38576 42792 23979 30168 32671 40258 26899 28549 24968 22836 31284 47652
 48813 48612 48308 36415 23370 48458 20493 20152 39884 48205 27051 42477
 21811 47802 34827 25637 23414 41337 44253 35045 36862 20651 28314 26215
 25399 45029 36561 37360 27351 25218 42650 29335 39011 46013 41530 20918
 32707 49380 40322 43881 47214 22622 49477 32429 38948 24434 24480 27566
 45885 28537 45140 20728 38130 34733 42803 37569 21649 33002 49800 44461
 46602 26698 22490 27697 44311 34494 38298 4

In [20]:
a=np.sum(DS_sal)
b=np.sum(DE_sal)
c=np.sum(DA_sal)
print('DS_department CTC:{}\nDE_Department CTC:{}\nDA_Department CTC:{}'.format(a,b,c))


DS_department CTC:6887413
DE_Department CTC:10331119.5
DA_Department CTC:7287413


In [21]:
a=sorted(DA_sal)[-10:]
b=sorted(DS_sal)[-10:]
c=sorted(DE_sal)[-10:]
print('''Top 10 DA Salaries:{}
Top 10 DS Salaries:{}
Top 10 DE Salaries:{}'''.format(a,b,c))

Top 10 DA Salaries:[50299, 50444, 50483, 50624, 50771, 50907, 51272, 51412, 51622, 51748]
Top 10 DS Salaries:[48299, 48444, 48483, 48624, 48771, 48907, 49272, 49412, 49622, 49748]
Top 10 DE Salaries:[72448.5, 72666.0, 72724.5, 72936.0, 73156.5, 73360.5, 73908.0, 74118.0, 74433.0, 74622.0]


In [22]:
print('''Sum of Top 10 DA Salaries:{}
Sum of Top 10 DS Salaries:{}
Sum of Top 10 DE Salaries:{}'''.format(sum(a),sum(b),sum(c)))

Sum of Top 10 DA Salaries:509582
Sum of Top 10 DS Salaries:489582
Sum of Top 10 DE Salaries:734373.0


In [23]:
l,l1,l2=[],[],[]
for i in a:
    l.append(np.count_nonzero(DA_sal==i))
for i in b:
    l1.append(np.count_nonzero(DS_sal==i))
for i in c:
    l2.append(np.count_nonzero(DE_sal==i))
print("Total count of DA employees with top 10 salaries: "+str(sum(l)))
print("Total count of DS employees with top 10 salaries: "+str(sum(l1)))
print("Total count of DE employees with top 10 salaries: "+str(sum(l2)))

Total count of DA employees with top 10 salaries: 10
Total count of DS employees with top 10 salaries: 10
Total count of DE employees with top 10 salaries: 10


Task7:
Provide  total number of employees having more than 40000 salary in all departments:

In [24]:
count1=np.count_nonzero(DA_sal>40000)
count2=np.count_nonzero(DS_sal>40000)
count3=np.count_nonzero(DE_sal>40000)
print("Total number of employees having more than 40000 salary in all departments: "+str(count1+count2+count3))

Total number of employees having more than 40000 salary in all departments: 299


Task8:
Increase the salary of all DS employees whose salary is less than 35000 by 20 %

In [25]:
for i in range(0,len(DS_sal)):
    if DS_sal[i]<35000:
        DS_sal[i]=DS_sal[i]+(DS_sal[i]*0.2)
DS_sal


array([24181, 45774, 37707, 33552, 42600, 29223, 36124, 47676, 41673,
       25652, 41269, 39728, 24668, 37430, 39265, 43601, 30931, 41558,
       31306, 28256, 49748, 47462, 45957, 32014, 34184, 49412, 49272,
       38738, 35546, 42552, 41451, 49622, 39334, 42788, 27151, 40460,
       38718, 34734, 41635, 33727, 48444, 38558, 36818, 32955, 36348,
       37862, 39290, 48907, 38716, 24603, 35299, 25452, 48771, 25108,
       42350, 25675, 44017, 40088, 44468, 47912, 46663, 47982, 42726,
       32586, 41476, 40591, 35408, 31953, 25756, 25324, 32077, 33058,
       36165, 26568, 40170, 37604, 27166, 43406, 31340, 38877, 42437,
       43614, 30622, 34380, 45255, 27124, 36148, 26215, 28549, 40300,
       37156, 40107, 40752, 41230, 40700, 40789, 46682, 40231, 30891,
       30782, 30157, 46456, 31405, 32702, 24217, 29937, 44731, 37951,
       35659, 36337, 36549, 48624, 46088, 36276, 39516, 27978, 36048,
       33217, 33721, 47946, 40126, 43877, 26803, 40119, 33489, 43149,
       44100, 38158,

Task9:
Delete records of the employees with emp id > 380 from DE department.

In [48]:
#condition=DE_emp<380
#DE_emp[condition]

In [52]:
DE_emp=np.delete(DE_emp,np.where(DE_emp>380))
DE_sal=np.delete(DE_sal,np.where(DE_emp>380))

In [53]:
DE_emp

array([201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213,
       214, 215, 216, 217, 218, 219, 220, 221, 222, 223, 224, 225, 226,
       227, 228, 229, 230, 231, 232, 233, 234, 235, 236, 237, 238, 239,
       240, 241, 242, 243, 244, 245, 246, 247, 248, 249, 250, 251, 252,
       253, 254, 255, 256, 257, 258, 259, 260, 261, 262, 263, 264, 265,
       266, 267, 268, 269, 270, 271, 272, 273, 274, 275, 276, 277, 278,
       279, 280, 281, 282, 283, 284, 285, 286, 287, 288, 289, 290, 291,
       292, 293, 294, 295, 296, 297, 298, 299, 300, 301, 302, 303, 304,
       305, 306, 307, 308, 309, 310, 311, 312, 313, 314, 315, 316, 317,
       318, 319, 320, 321, 322, 323, 324, 325, 326, 327, 328, 329, 330,
       331, 332, 333, 334, 335, 336, 337, 338, 339, 340, 341, 342, 343,
       344, 345, 346, 347, 348, 349, 350, 351, 352, 353, 354, 355, 356,
       357, 358, 359, 360, 361, 362, 363, 364, 365, 366, 367, 368, 369,
       370, 371, 372, 373, 374, 375, 376, 377, 378, 379, 380])

In [54]:
DE_emp_new=np.arange(701,706)
#DE_emp.append(DE_emp_new)
DE_emp=np.append(DE_emp,DE_emp_new)
DE_emp

array([201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213,
       214, 215, 216, 217, 218, 219, 220, 221, 222, 223, 224, 225, 226,
       227, 228, 229, 230, 231, 232, 233, 234, 235, 236, 237, 238, 239,
       240, 241, 242, 243, 244, 245, 246, 247, 248, 249, 250, 251, 252,
       253, 254, 255, 256, 257, 258, 259, 260, 261, 262, 263, 264, 265,
       266, 267, 268, 269, 270, 271, 272, 273, 274, 275, 276, 277, 278,
       279, 280, 281, 282, 283, 284, 285, 286, 287, 288, 289, 290, 291,
       292, 293, 294, 295, 296, 297, 298, 299, 300, 301, 302, 303, 304,
       305, 306, 307, 308, 309, 310, 311, 312, 313, 314, 315, 316, 317,
       318, 319, 320, 321, 322, 323, 324, 325, 326, 327, 328, 329, 330,
       331, 332, 333, 334, 335, 336, 337, 338, 339, 340, 341, 342, 343,
       344, 345, 346, 347, 348, 349, 350, 351, 352, 353, 354, 355, 356,
       357, 358, 359, 360, 361, 362, 363, 364, 365, 366, 367, 368, 369,
       370, 371, 372, 373, 374, 375, 376, 377, 378, 379, 380, 70