In [1]:
import numpy as np

In [2]:
arr1=np.arange(1,11);arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
np.mean(arr1)

5.5

In [4]:
np.median(arr1)

5.5

In [5]:
np.std(arr1)

2.8722813232690143

In [6]:
arr2=np.random.randint(1,9,(3,3));arr2

array([[2, 1, 4],
       [6, 8, 8],
       [2, 7, 8]])

In [7]:
arr3=arr2.flatten();arr3

array([2, 1, 4, 6, 8, 8, 2, 7, 8])

In [8]:
np.transpose(arr2)

array([[2, 6, 2],
       [1, 8, 7],
       [4, 8, 8]])

In [9]:
arr4=np.arange(10);arr4

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
arr4[5]

5

In [11]:
arr4[2:8]

array([2, 3, 4, 5, 6, 7])

In [12]:
arr4[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [13]:
arr5=np.arange(1,10).reshape(3,3);arr5

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
arr5*2

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [15]:
arr6=np.dot(arr5,arr5);arr6

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [16]:
arr6=np.matmul(arr5,arr2);arr6

array([[ 20,  38,  44],
       [ 50,  86, 104],
       [ 80, 134, 164]])

In [17]:
a=np.arange(1,10).reshape(3,3);a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
b=np.arange(1,10).reshape(3,3);b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
np.dot(a,b)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [20]:
np.linalg.det(a)

-9.51619735392994e-16

In [21]:
np.linalg.inv(b)

array([[ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15],
       [-6.30503948e+15,  1.26100790e+16, -6.30503948e+15],
       [ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15]])

In [22]:
a1=np.arange(1,37).reshape(6,6);a1

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]])

In [23]:
np.diag(a1)

array([ 1,  8, 15, 22, 29, 36])

In [24]:
np.flipud(np.diag(np.fliplr(a1)))

array([31, 26, 21, 16, 11,  6])

In [25]:
a1[a1%3==0]

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36])

In [26]:
a2=np.random.randint(1,100,1000);a2

array([ 4, 95, 44, 38, 41, 60, 72, 29,  1, 70, 56,  8, 89, 21, 25, 57, 52,
       89, 74, 61, 54, 44, 96, 45, 47, 97, 45, 60, 79, 27,  9, 54, 20, 99,
        2, 74, 16, 57, 52,  3, 48, 55, 29, 59, 86, 35, 98, 28, 62, 52,  3,
       72, 83, 87, 99, 85, 47, 98, 77, 85, 72, 19, 87, 49,  9, 12, 33, 19,
       90, 67,  4, 92, 54, 38, 52, 21, 53, 37, 35,  7, 37, 70, 81, 18, 26,
       73, 97, 20,  3, 73, 16, 78,  8, 37, 65, 56, 79,  8, 32, 89, 54, 29,
       18,  5,  2, 62, 72, 13, 44, 33,  2, 29, 94, 82,  4, 96, 50, 44, 58,
       45, 60, 30, 65, 90, 42, 59, 49, 27, 44, 70, 85, 12, 10, 96,  2, 16,
       53, 57, 11, 23, 22, 27, 36, 31,  7, 23, 98, 99, 94, 87, 96,  5, 71,
       91, 64, 92, 92, 46, 21, 80, 61, 31, 43, 59, 28,  9, 41, 59, 88,  3,
       32, 38, 99, 12, 40, 66, 43, 34,  1,  6, 67, 77, 36,  4,  7, 86, 94,
       88, 53, 78, 74, 53, 27, 69, 13, 66,  3, 74, 33, 51, 33, 44, 30, 62,
       63, 80, 24, 74,  3, 45, 28, 87, 95, 15, 11, 79, 65, 29, 16, 23, 23,
       56, 19, 62, 35, 26

In [27]:
np.mean(a2)

49.456

In [28]:
np.median(a2)

48.5

In [29]:
np.std(a2)

28.289857970657966

In [30]:
sample=np.random.choice(a2,size=100,replace=True);sample

array([47, 17, 51, 75,  2, 89, 92,  8, 94,  1, 19, 45, 92, 15, 64, 11, 57,
       58, 90, 66, 62, 35, 23, 33, 74, 63, 31, 88, 68, 22, 99, 47, 33,  9,
       59, 61, 48, 79, 18, 39, 69, 98, 83, 19, 45, 97, 47, 29, 17, 81, 33,
       23, 86, 25, 66, 38,  9, 78,  8, 52, 31, 72, 17, 23, 25, 76, 45, 26,
       33, 86, 60, 12, 21, 59, 94, 52, 49, 53,  7, 21, 42, 32, 61, 30, 62,
       88, 64, 62, 15, 83, 81, 44, 23, 48, 74, 20, 39, 49, 12, 56])

In [31]:
np.percentile(sample,[2.5,97.5])

array([ 7.475, 95.575])

In [32]:
product_ids = np.array([1, 2, 3, 4, 5])
quantities = np.array([10, 15, 5, 8, 12])
prices = np.array([20.5, 10.2, 15.8, 12.6, 18.9])

In [33]:
a1=np.array(quantities*prices);a1

array([205. , 153. ,  79. , 100.8, 226.8])

In [34]:
product_ids[np.argmax(a1)]

5

In [35]:
np.mean(prices)/np.sum(quantities)

0.312