# 23-June-2023 Numpy

In [7]:
#import numpy package and create a integer array

import numpy as np

a=np.array([1,0,3,4,7,6]).reshape(2,3)

In [11]:
a.sort(axis=0);a

array([[1, 0, 3],
       [4, 7, 6]])

In [13]:
a=np.array([[1,2,5],[2,8,3]]);a


array([[1, 2, 5],
       [2, 8, 3]])

In [15]:
print(np.sort(a,axis=1))

[[1 2 5]
 [2 3 8]]


In [17]:
a.sort(axis=0);a

array([[1, 2, 3],
       [2, 8, 5]])

In [2]:
#if we wish we can specify the type of array
a3=np.array([1.0,2.1,3.1],float)

In [3]:
#obtain an array of desired datatype
a3=np.array([1.0,2.1,3.2],int)

In [4]:
#array is homogeneous 
#it doesnt mean it cant have multiple datatype values inside it , it converts all other datatype to the highest precendence type

a4=np.array([2,3,4,5,6.0,'string1'])

In [5]:
a4.dtype

dtype('<U32')

In [6]:
#2D array create a array with 2 rows and 3 columns

array21=np.array([[1,2,3],[4,5,6]])

In [7]:
array21

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
array1=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

In [10]:
array1.ndim

3

In [11]:
#creating a complex array

array3=np.array([[1,2,3],[4,5,6]],complex)

In [12]:
array3

array([[1.+0.j, 2.+0.j, 3.+0.j],
       [4.+0.j, 5.+0.j, 6.+0.j]])

# Creation of Filler Array

In [13]:
#we can create numpy arrays which contain initial placeholders values, which can be replaced later

#creating a empty array or create 2D array
# empty gives garbage values

a9=np.empty((2,3))

In [14]:
a9

array([[0., 0., 0.],
       [0., 0., 0.]])

In [15]:
a10=np.empty([2,3])
a10

array([[0., 0., 0.],
       [0., 0., 0.]])

In [16]:
#create 2D array of zeros
a11=np.zeros((2,3));a11  # after ; we can directly provide values to print

array([[0., 0., 0.],
       [0., 0., 0.]])

In [18]:
a12=np.ones((2,4),int);a12

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

In [20]:
#create a array with same value
arr1=np.full((2,3),5)
arr1

array([[5, 5, 5],
       [5, 5, 5]])

In [23]:
#random.random or random.rand ( gives float values btw 0 - 1 )
#random.randint(start,end,step) (gives values btw start and end)

arra2=np.random.random(5) #1D
#arra2=np.random.rand((5,5)) #2D
arra2

array([0.94946681, 0.98596668, 0.12725289, 0.41283257, 0.03433819])

In [24]:
#create array with arange function

arra3=np.arange(2,5)
arra3

array([2, 3, 4])

In [25]:
type(arra3)

numpy.ndarray

In [26]:
#create a array with arange function with specified steps

arra4=np.arange(2,20,2)
arra4

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [27]:
#using linspace #linear spacing btw starting and ending 

array23=np.linspace(1,10,5) # 5 is not step , its the number of elements required
array23 

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [30]:
arra=np.arange(1,10,5)
arra

array([1, 6])

In [31]:
#In numpy we can create identity matrix using the np.eye function

ar1=np.eye(4)
ar1

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [33]:
#using np.identity function

ar2=np.identity((5),int)
ar2

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [34]:
a1=np.array([[[2,4,7,8],[2,5,8,6]],[[3,8,6,4],[8,6,4,9]],[[2,9,6,8],[6,7,2,9]]])
a1

array([[[2, 4, 7, 8],
        [2, 5, 8, 6]],

       [[3, 8, 6, 4],
        [8, 6, 4, 9]],

       [[2, 9, 6, 8],
        [6, 7, 2, 9]]])

In [35]:
#shape of the array
a1.shape # dimension (i.e., number of sub-arrays) , rows, columns (rows and columns in a sub-array)

(3, 2, 4)

In [40]:
#reshape the array
a2=a1.reshape(6,4)
a2

array([[2, 4, 7, 8],
       [2, 5, 8, 6],
       [3, 8, 6, 4],
       [8, 6, 4, 9],
       [2, 9, 6, 8],
       [6, 7, 2, 9]])

In [41]:
a3=a1.reshape(2,4,3);a3

array([[[2, 4, 7],
        [8, 2, 5],
        [8, 6, 3],
        [8, 6, 4]],

       [[8, 6, 4],
        [9, 2, 9],
        [6, 8, 6],
        [7, 2, 9]]])

In [42]:
a3.ndim

3

In [45]:
# 3 dimension is a array that contains array of 2- dimension arrays

#n[(n-1) dimensions]

print(a3.itemsize) #gives the byte value of the array type
a3.size # gives the number of items

4


24

In [53]:
#create 2 arrays a1 and a2
a1=np.array([[1,2,3,4],[5,6,7,8]])
a2=[[1.0,1.0,1.0,1.0],[2.0,2.0,2.0,2.0]]

In [54]:
sum1=np.add(a1,a2)

In [55]:
sum

array([[ 2.,  3.,  4.,  5.],
       [ 7.,  8.,  9., 10.]])

In [61]:
diff=np.subtract(a1,a2) ;diff

array([[0., 1., 2., 3.],
       [3., 4., 5., 6.]])

In [64]:
mul=np.multiply(a1,a2);mul

array([[ 1.,  2.,  3.,  4.],
       [10., 12., 14., 16.]])

In [76]:
div=np.divide(a2,a1);
print(div)
div1=a2//a1;
print(div1)

[[1.         0.5        0.33333333 0.25      ]
 [0.4        0.33333333 0.28571429 0.25      ]]
[[1. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [68]:
mod=a1%a2;mod

array([[0., 0., 0., 0.],
       [1., 0., 1., 0.]])

In [70]:
power1=np.power(a1,2);power1

array([[ 1,  4,  9, 16],
       [25, 36, 49, 64]], dtype=int32)

In [72]:
#scalar operation with array

print(a1)
print(a1+2)

[[1 2 3 4]
 [5 6 7 8]]
[[ 3  4  5  6]
 [ 7  8  9 10]]


# Statistical Operations

In [77]:
a1=np.array([[1,2,3],[4,5,6]])

In [78]:
np.sum(a1) #sum of all elements in an array

21

In [80]:
print(a1)
print(a1.min())
print(a1.max())
print(a1.max(axis=0)) # in array 0 is column 
print(a1.max(axis=1)) # 1 is row
print(a1.min(axis=0))
print(a1.min(axis=1))
print(a1.cumsum(axis=0))

[[1 2 3]
 [4 5 6]]
1
6
[4 5 6]
[3 6]
[1 2 3]
[1 4]
[[1 2 3]
 [5 7 9]]


In [86]:
print(np.mean(a1))
print(np.median(a1))
print(np.corrcoef(a1))
print(np.std(a1))
print(np.count_nonzero(a1==2)) # gives number which is repeated that many number of times

3.5
3.5
[[1. 1.]
 [1. 1.]]
1.707825127659933
1


# Linear Algebra Operations:


In [88]:
#multiply corresponding elements of a1 and a2

#columns of first array and rows of second array should be same

#transpose
k=np.transpose(a1);
k

array([[1, 4],
       [2, 5],
       [3, 6]])

In [90]:
#trace of a matrix is sum of its diagonal elements

s=np.trace(a1)
print(a1)
s

[[1 2 3]
 [4 5 6]]


6

In [92]:
#inverse of a matrix

a=np.array([[1,2],[3,4]])
b=np.linalg.inv(a)
b

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

# Bitwise Operations

In [ ]:
a1=np.array([[1,2,3,4],[5,6,7,8]])

In [95]:
a=np.array([[3,3,7],[1,5,2]])

In [96]:
b=a #no copy # refers to same object

In [97]:
b

array([[3, 3, 7],
       [1, 5, 2]])

In [99]:
#Original array

Original_array=np.array([[3,3,7],[1,5,2]])
shallow_copy=Original_array.view() #view() is the function to create shallow copy 
# original array changes if any changes made in shallow copy
shallow_copy[0][0]=20

In [101]:
Original_array

array([[20,  3,  7],
       [ 1,  5,  2]])

In [102]:
#deep copy
Original_array=np.array([[3,3,7],[1,5,2]])
deepCopy=Original_array.copy() # new copy of an array but doesn't change the original array
deepCopy[1][1]=100

In [103]:
Original_array

array([[3, 3, 7],
       [1, 5, 2]])

In [109]:
#sort array
a.sort()  #sorts row-wise
a

array([[1, 2, 5],
       [3, 3, 7]])

In [111]:
b.sort(axis=0) #sorts column-wise
b

array([[1, 2, 5],
       [3, 3, 7]])

In [112]:
np.array_equal(a,b) #checks entire elements and shape

True

In [1]:
array1=np.array([[2,4,7,8],[2,5,8,6],[3,4,5,6]])

array1[:3,2:4] #rows,columns


NameError: name 'np' is not defined

In [115]:
#flatten() , ravel()

In [ ]:
np.array([1,2,3,4])

In [119]:
print(a)
print("----------")
print(b)

[[1 2 5]
 [3 3 7]]
----------
[[1 2 5]
 [3 3 7]]


In [116]:
np.append(a,b) # gives as a single dimension

array([1, 2, 5, 3, 3, 7, 1, 2, 5, 3, 3, 7])

In [117]:
np.append(a,b,axis=0) #append as column wise

array([[1, 2, 5],
       [3, 3, 7],
       [1, 2, 5],
       [3, 3, 7]])

In [120]:
np.append(a,b,axis=1) #append as row wise

array([[1, 2, 5, 1, 2, 5],
       [3, 3, 7, 3, 3, 7]])

# Splitting and stacking

In [121]:
data=np.arange(24)

In [142]:
data2=data.reshape(6,4)

In [143]:
print(data2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [130]:
data2.ndim

2

In [146]:
data1=np.vsplit(data2,3)
data1

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]]),
 array([[16, 17, 18, 19],
        [20, 21, 22, 23]])]

In [147]:
data3=np.hsplit(data2,2)
data3

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13],
        [16, 17],
        [20, 21]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15],
        [18, 19],
        [22, 23]])]

In [148]:
b1=np.array([[3,5,8],[4,5,2]])
b2=np.array([[7,8,4],[5,6,1]])

In [158]:
b3=np.vstack((b1,b2));b3 #vertical stack

array([[3, 5, 8],
       [4, 5, 2],
       [7, 8, 4],
       [5, 6, 1]])

In [159]:
b4=np.hstack((b1,b2));b4 #horizontal stack

array([[3, 5, 8, 7, 8, 4],
       [4, 5, 2, 5, 6, 1]])

In [160]:
#delete element

delarray=np.array([1,2,3,4,5,6,7,8,9,0])
ad1=np.delete(delarray,4)

In [162]:
ad1

array([1, 2, 3, 4, 6, 7, 8, 9, 0])

In [164]:
#delete columns - syntax np.delete(arrayname,index,axis=1) (only here axis=1 is column)
ad4=np.delete(b4,2,axis=1);ad4

array([[3, 5, 7, 8, 4],
       [4, 5, 5, 6, 1]])

In [166]:
#delete rows - syntax np.delete(arrayname,index,axis=0) (only here axis=0 is row)
ad5=np.delete(b3,2,axis=0)
ad5

array([[3, 5, 8],
       [4, 5, 2],
       [5, 6, 1]])