In [4]:
import pandas as pd

In [5]:
data = {'Name': ['Alice', 'Bob', 'Charlie', 'Dave'],'Score': [85, 92, 78, 95]}

In [7]:
df=pd.DataFrame(data , index=['s1','s2','s3','s4']);df

Name  Score
s1    Alice     85
s2      Bob     92
s3  Charlie     78
s4     Dave     95

In [14]:
df[df['Score']>90].sort_values(by='Score',ascending=False)

Name  Score
s4  Dave     95
s2   Bob     92

In [15]:
data1 = {'Product': ['A', 'B', 'A', 'B', 'C'],
        'Category': ['X', 'Y', 'X', 'Y', 'Z'],
        'Sales': [100, 200, 150, 300, 250],
        'Price': [10, 20, 15, 25, 30]}

In [17]:
df1=pd.DataFrame(data1);df1

Product Category  Sales  Price
0       A        X    100     10
1       B        Y    200     20
2       A        X    150     15
3       B        Y    300     25
4       C        Z    250     30

In [22]:
df1.groupby('Category').agg({'Sales':'sum','Price':'mean'})

Sales  Price
Category              
X           250   12.5
Y           500   22.5
Z           250   30.0

In [2]:
a=[[1,2,3],[4,5,6]]
b=[[3,4,5],[1,2,3]]

In [3]:
import numpy as np

In [4]:
a1=np.array(a)

In [5]:
a1

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
a2=np.array(b)

a2

In [7]:
a2

array([[3, 4, 5],
       [1, 2, 3]])

In [8]:
a3=a1+a2

In [9]:
a3=np.array(a3)
a3=np.vstack((a1,a2))

In [10]:
print(a3)

[[1 2 3]
 [4 5 6]
 [3 4 5]
 [1 2 3]]


In [11]:
a4=np.concatenate((a1,a2),axis=1)

In [12]:
a4

array([[1, 2, 3, 3, 4, 5],
       [4, 5, 6, 1, 2, 3]])

In [13]:
import numpy as np

a = np.array([[1, 2], [3, 4]])

b = np.array([[5, 6],[7, 8]])

c = np.vstack((a, b))

print(c)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [14]:
a

array([[1, 2],
       [3, 4]])